### PR TITLE
[App] add hack to open links from markdown in a new tab

### LINKED ISSUE #212: [App] Consider opening artist's links always in new tab
### description
* at artwork detail artist's names are linked to their website
* Link for Main Artist Name opens in a new tab
* Link in description opens in the same window

### solution
* **optional:** consider opening always in new tab.
* **must-have:** have same behaviour throughout whole app.
* done via adding `target="_blank" rel="noopener`

### PR DESCRIPTION
**Pull request by moritzpflueger**
quite hacky, because I use plain Javascript in the `ArtworkDetail` `mounted ()` hook, but it gets the job done for now.

result: all links from description are now being added the `_target` attribute and thus opened in a new tab.

closes #212

### CODE REVIEW

**Review by milanbargiel — CHANGES_REQUESTED** [review]
Hacks make life a lot easier :)

Two things:
1. Why do you iterate over all links? Wouldn't it be enough to search for links in the artwork description text?
2. The code does not work for now. In the if-query you exclude links that have an `<u>` tag `!link.innerHTML.includes('<u>')`. But those are exactly the elements we are trying to address?

**Comment by moritzpflueger** [comment]
Damn, you're right. I tested this and it didn't work for me either. Thanks for testing!

* It worked while being in development mode and working on the code locally. On reload hoewever my "hack" was never called.

I invested 15 minutes and can't find out, why this is happening. Let's postpone this for now as it's not thaat critical.

**Comment by moritzpflueger** [comment]
Alright, the updated version is no longer a hack, but actually pretty cool :-) let me explain ...

From Strapi we get the artwork's description that might include a link to the artist's website. The format is `[label](url)`.

This gets transcripted into a html `<a>` tag inside the `Vue Markdown` component. However, we wanted to include `target="_blank" rel="noopener"` to make links open in a new tab (all external links are opened in a new tab at Kulturgenerator).

We have to do so **before** injecting the description into `vue-markdown`. So I made the description a computed property and applied the following logic:

If the pattern `[label](url)` replace it with the pattern `a href="url" target="_blank" rel="noopener">label</a>`

That's where Regex comes in quite handy. I found a regex pattern that will find the markdown link pattern.

regex is quite magical. The result gets split up into two groups (group1= $1, group2 = $2) and can easily injected in to the replacement object.

To test this visit https://regexr.com/
* paste `\[(.*?)\]\((.*?)\)` into the header
* paste test description into the body
```
[<u>Kriz Olbrichts</u>](https://krizolbricht.wordpress.com/) (*1986) Arbeiten mäandern zwischen Malerei, Bildhauerei, Sound, Fotografie – kurz: zwischen Material, Handlung und Raum. Ein Großteil seiner Arbeiten ist ortsbezogen und konstituiert sich sich oftmals erst durch den Ort seiner Präsentation. Definitionen, Zuschreibungen und Immanenzen von Kunst werden auf jeweils ganz eigene Weise reflektiert. Teil von Kriz Olbrichts künstlerischer Praxis sind auch kuratorische Tätigkeiten als Begründer und Betreiber von Projekträumen wie seit 2017 im Kuratorium der Simultanhalle in Köln.
```

* observe that the html markdown link gets highlighted.

image

i LOVE it! <3

**Review by milanbargiel — APPROVED** [review]
Good job, very simple and just a few lines of code.
Nice one!

**Pull request merged**
